stages:
  - build

build_docker_image:
  stage: build
  image: docker:26.1.4-cli

  services:
    - docker:dind

  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    image: rajvi04sf/portofolioweb_rajvi_fatingan:latest

  before_script:
    - docker login -u "$DOCKER_HUB_USERNAME" --password "$DOCKER_HUB_PASSWORD"


  script:
    - docker build --pull -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"

