services:
  server:
    container_name: portfolio_frontend
    build:
      context: .
      dockerfile: Dockerfile
    image: rajvi04sf/portofolioweb_rajvi_fatingan:latest
    environment:
      - PORT=3000
    networks:
      - proxy-network
    restart: unless-stopped

networks:
  proxy-network:
    external: true