services:
  server:
    container_name: portfolio-site_frontend
    build:
      context: .
      dockerfile: Dockerfile
    image: rajvi04sf/portofolioweb_rajvi_fatingan:latest
    ports:
      - "80:80"
    restart: unless-stopped